server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/easyorder
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /api-docs
cloudinary:
  cloud-name: dohgdvnuy
  api-key: 629845858442262
  api-secret: gB6Ld8Agabga0TuyOH1RD9_2BG0
jwt:
  signerKey: "YvaC4YtaTbPJ9kjAPkauqZ1HlkaqvAkz5jVeaxTGUTpm9YoNVGTU2c98XnWsQo6BLQ9h5n4HcySt0UcvmbBXiL0PpCedzXBxAn3+5FD83H4="